2017-10-24 20:07:05,766 [Thread-4:7240] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/fa2c5fde-b8ab-11e7-bd6f-80fa5b4b55e4.png
2017-10-24 20:07:05,776 [Thread-5:4540] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/004cac40-b8ac-11e7-9603-80fa5b4b55e4.png
2017-10-24 20:08:17,480 [Thread-10:9264] [django.request:152] [base:get_response] [WARNING]- Not Found: /archive/index.html
2017-10-24 20:13:13,223 [Thread-9:12124] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/a17e6e40-b8ad-11e7-b3a5-80fa5b4b55e4.jpg
2017-10-24 21:09:59,665 [Thread-8:11416] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\blog\views.py", line 42, in index
    return render(request, 'index.html', locals())
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\defaultfilters.py", line 639, in slice_filter
    for x in arg.split(':'):
AttributeError: 'int' object has no attribute 'split'
2017-10-24 22:39:12,723 [Thread-2:4848] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\blog\views.py", line 42, in index
    return render(request, 'index.html', locals())
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "c:\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\demo\django\blog_project\myblog\blog\templatetags\myfilter.py", line 16
    if a.isdigit()
                 ^
SyntaxError: invalid syntax
2017-10-24 22:39:36,993 [Thread-2:6948] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\blog\views.py", line 42, in index
    return render(request, 'index.html', locals())
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "c:\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\demo\django\blog_project\myblog\blog\templatetags\myfilter.py", line 16
    if a.isdigit()
                 ^
SyntaxError: invalid syntax
2017-10-24 22:39:41,611 [Thread-3:4000] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\blog\views.py", line 42, in index
    return render(request, 'index.html', locals())
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\template\backends\django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "c:\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\demo\django\blog_project\myblog\blog\templatetags\myfilter.py", line 16
    if a.isdigit()
                 ^
SyntaxError: invalid syntax
2017-10-24 22:44:32,805 [Thread-3:11172] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/421820e1-b8ad-11e7-8eaf-80fa5b4b55e4.jpg
2017-10-24 22:44:51,628 [Thread-11:9700] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/421820e1-b8ad-11e7-8eaf-80fa5b4b55e4.jpg
2017-10-25 21:11:21,862 [Thread-3:5320] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 21:25:39,913 [Thread-2:12092] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\contrib\admin\sites.py", line 214, in inner
    if request.path == reverse('admin:logout', current_app=self.name):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'logout' with no arguments not found. 1 pattern(s) tried: [u'admin/$logout/$']
2017-10-25 21:25:47,084 [Thread-4:7084] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\contrib\admin\sites.py", line 214, in inner
    if request.path == reverse('admin:logout', current_app=self.name):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'logout' with no arguments not found. 1 pattern(s) tried: [u'admin/$logout/$']
2017-10-25 21:26:11,381 [Thread-2:10872] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:26:12,684 [Thread-3:9516] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:26:14,608 [Thread-4:4020] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:26:17,101 [Thread-5:6676] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:26:23,625 [Thread-2:3092] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:26:25,884 [Thread-3:1400] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:27:04,946 [Thread-2:7528] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:27:15,706 [Thread-2:6072] [django.request:152] [base:get_response] [WARNING]- Not Found: /admin/
2017-10-25 21:29:49,549 [Thread-3:6776] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\contrib\admin\sites.py", line 214, in inner
    if request.path == reverse('admin:logout', current_app=self.name):
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\demo\django\blog_project\myblog\myblog_venv\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'logout' with no arguments not found. 1 pattern(s) tried: [u'admin/$logout/$']
2017-10-25 21:36:17,190 [Thread-25:7808] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:00:59,141 [Thread-3:12056] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/421820e1-b8ad-11e7-8eaf-80fa5b4b55e4.jpg
2017-10-25 22:01:05,352 [Thread-15:10252] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/421820e1-b8ad-11e7-8eaf-80fa5b4b55e4.jpg
2017-10-25 22:01:12,016 [Thread-17:4804] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/f2094930-b8ac-11e7-87db-80fa5b4b55e4.jpg
2017-10-25 22:06:14,033 [Thread-72:12928] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/a17e6e40-b8ad-11e7-b3a5-80fa5b4b55e4.jpg
2017-10-25 22:07:24,562 [Thread-88:8644] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/421820e1-b8ad-11e7-8eaf-80fa5b4b55e4.jpg
2017-10-25 22:08:04,809 [Thread-104:8100] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/421820e1-b8ad-11e7-8eaf-80fa5b4b55e4.jpg
2017-10-25 22:08:16,694 [Thread-117:3888] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/f2094930-b8ac-11e7-87db-80fa5b4b55e4.jpg
2017-10-25 22:09:28,312 [Thread-138:11996] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/f2094930-b8ac-11e7-87db-80fa5b4b55e4.jpg
2017-10-25 22:09:44,398 [Thread-155:11716] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/a8082040-b8ac-11e7-8fb6-80fa5b4b55e4.png
2017-10-25 22:10:21,862 [Thread-169:3888] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/fa2c5fde-b8ab-11e7-bd6f-80fa5b4b55e4.png
2017-10-25 22:10:21,865 [Thread-170:9768] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/004cac40-b8ac-11e7-9603-80fa5b4b55e4.png
2017-10-25 22:10:51,964 [Thread-180:9432] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/b46d42e1-b8aa-11e7-bf67-80fa5b4b55e4.jpg
2017-10-25 22:10:51,966 [Thread-181:10212] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/dbbda740-b8aa-11e7-a8d9-80fa5b4b55e4.jpg
2017-10-25 22:10:51,966 [Thread-182:2744] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/ebaaa62e-b8aa-11e7-a161-80fa5b4b55e4.jpg
2017-10-25 22:10:51,967 [Thread-183:12976] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/kindeditor/2017/10/fda9470f-b8aa-11e7-a42c-80fa5b4b55e4.jpg
2017-10-25 22:48:00,464 [Thread-13:7272] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:48:16,973 [Thread-24:4068] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:48:21,621 [Thread-28:12792] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:48:28,456 [Thread-37:4980] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:48:42,174 [Thread-58:6052] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:48:46,444 [Thread-66:10784] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 22:48:48,806 [Thread-70:11756] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 23:01:24,882 [Thread-18:6120] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 23:13:17,961 [Thread-10:7092] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.sina.com
2017-10-25 23:13:17,959 [Thread-9:8360] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.qq.com
2017-10-25 23:13:17,960 [Thread-8:6620] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.baidu.com
2017-10-25 23:13:17,960 [Thread-11:6668] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://maiziedu.com
2017-10-25 23:13:18,178 [Thread-25:8328] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-10-25 23:14:40,710 [Thread-12:4200] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://maiziedu.com
2017-10-25 23:14:40,713 [Thread-10:7528] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.qq.com
2017-10-25 23:14:40,716 [Thread-9:4392] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.baidu.com
2017-10-25 23:14:40,720 [Thread-11:6184] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.sina.com
2017-10-25 23:15:06,362 [Thread-8:12204] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.baidu.com
2017-10-25 23:15:06,364 [Thread-9:6676] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.qq.com
2017-10-25 23:15:06,364 [Thread-10:6392] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://www.sina.com
2017-10-25 23:15:06,364 [Thread-11:864] [django.request:152] [base:get_response] [WARNING]- Not Found: /uploads/http://maiziedu.com
2017-10-25 23:16:55,170 [Thread-53:1708] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-11-13 19:02:34,921 [Thread-8:8108] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-01-19 21:18:01,403 [Thread-19:10180] [django.request:152] [base:get_response] [WARNING]- Not Found: /adin
2018-01-19 21:18:05,325 [Thread-20:15288] [django.request:152] [base:get_response] [WARNING]- Not Found: /adin
2018-01-19 21:21:46,382 [Thread-3:6504] [django.request:152] [base:get_response] [WARNING]- Not Found: /xadmin/
2018-01-19 21:25:42,043 [Thread-89:10180] [django.request:152] [base:get_response] [WARNING]- Not Found: /article/index.html
